---

- name: Restart mailcow
  become: yes
  docker_compose:
    project_src: "{{ mailcow__install_path }}"
    project_name: mailcowdockerized
    restarted: yes
    state: present

- name: Recreate mailcow
  become: yes
  docker_compose:
    project_src: "{{ mailcow__install_path }}"
    project_name: mailcowdockerized
    recreate: smart
    state: present
